### ISSUE TITLE
indent tags, not attributes, for html files

### ISSUE THREAD

**Issue by mlarcher** [ck86/gulp-lintspaces#11]
When dealing with html files, it's often useful to align the attributes of a given tag together. As the tag name vary in length, this implies that the lines beginning with an attribute will not comply with the indentation setting. This is usually handled by editorconfig based plugins, but is treated as an error by gulp-lintspaces.

**Comment by ck86** [comment]
Please report this issue directly to [lintspaces](https://github.com/schorfES/node-lintspaces).
